package constant

// CONFIGURATION
const SERVER_KONVEN="SERVER.KONVEN"
const SERVER_SYARIAH="SERVER.SYARIAH"
const SERVER_GALERI="SERVER.G24"
const SERVER_KONVEN_DRC="SERVER.KONVEN.DRC"
const SERVER_SYARIAH_DRC="SERVER.SYARIAH.DRC"
const SERVER_GALERI_DRC="SERVER.G24.DRC"

const PREFIX_BRANCH_KONVEN = "1"
const PREFIX_BRANCH_GALERI = "5"
const PREFIX_BRANCH_SYAR = "6"
const PREFIX_BRANCH_PUSAT_KONVEN = "00002"
const PREFIX_BRANCH_PUSAT_SYAR = "00003"
const PREFIX_BRANCH_PUSAT_GALERI = "00004"
const PREFIX_MIGRASI_KONVEN = "90"
const PREFIX_MIGRASI_SYAR = "91"
const FLAG_KONVEN = "K"
const FLAG_SYAR = "S"
const FLAG_GALERI = "G"

// RESPONSE CODE
const CODE_HTTP_NOT_FOUND = "X4"
const CODE_HTTP_INTERNAL_ERROR = "X5"
const CODE_APPROVED = "00"
const CODE_INVALID_TRANSACTION = "12"
const CODE_INVALID_AMOUNT = "13"
const CODE_ACCOUNT_NOT_FOUND = "14"
const CODE_INVALID_ACCOUNT = "15"
const CODE_WRONG_FORMAT = "30"
const CODE_INVALID_CLIENT = "31"
const CODE_TIMEOUT = "68"
const CODE_INVALID_BILL = "88"
const CODE_CUT_OFF_TIME = "90"
const CODE_SYSTEM_MAINTENANCE = "96"
const CODE_GENERAL_ERROR = "98"

// RESPONSE DESC
const DESC_APPROVED = "Approved"
const DESC_HTTP_NOT_FOUND = "There is No Resource Path"
const DESC_HTTP_INTERNAL_ERROR = "Service Internal Error"
const DESC_INVALID_TRANSACTION = "Invalid Transaction"
const DESC_INVALID_AMOUNT = "Invalid Amount"
const DESC_ACCOUNT_NOT_FOUND = "Account Not Found"
const DESC_INVALID_ACCOUNT = "Invalid Account"
const DESC_WRONG_FORMAT = "Wrong Format"
const DESC_INVALID_CLIENT = "Invalid Client"
const DESC_TIMEOUT = "Transaction Timeout"
const DESC_INVALID_BILL = "Invalid Bill"
const DESC_CUT_OFF_TIME = "Cut Off Time"
const DESC_SYSTEM_MAINTENANCE = "System Maintenance"
const DESC_GENERAL_ERROR = "General Error"

// ROLE
const AGEN = "agen"
const CHANNELING = "channeling"
const CUSTOMER = "customer"
const CUSTOMER_CHANNEL = "customerchannel"
const DEALER = "dealer"
const DEPOSIT = "deposit"
const GADAI = "gadai"
const GTE = "gte"
const JSWITCH = "jswitch"
const LEAD = "lead"
const MIKRO = "mikro"
const MIKRO_CHANNEL = "mikrochanneling"
const MIKRO_SYARIAH = "mikrosyariah"
const MULIA = "mulia"
const MULTI_PAYMENT_ONLINE = "mpo"
const OTP = "otp"
const PARAMETER = "param"
const PORTOFOLIO = "portofolio"
const PROMO = "promo"
const RAHN = "rahn"
const RTE = "rte"
const SAP = "sap"
const TABUNGAN = "tabunganemas"
const TABUNGAN_CHANNEL = "tabunganchannel"
const TRANSAKSI = "transaksi"
const VA_PEGADAIAN = "va"

// REQUEST TYPE
const AKTIVASI = "AKTIVASI"
const BOOKING = "BOOKING"
const CASHOUT = "CASHOUT"
const CHECK = "CHECK"
const DISBURSAL = "DISBURSAL"
const INQUIRY = "INQUIRY"
const PAYMENT = "PAYMENT"
const POSTING = "POSTING"
const REGISTER = "REGISTER"

// ERROR SYSTEM
const ERR_DATABASE = "Error Database"
const ERR_ROWS_PARSING = "Error Parsing Rows Results"

// ERROR MESSAGE
const MSG_ERR_REQ_BODY = "Error IO Read Request Body"
const MSG_ERR_RES_BODY = "Error IO Read Response Body"
const MSG_ERR_JSON_PARSING_REQ = "Error Parsing JSON Request Body"
const MSG_ERR_JSON_PARSING_RES = "Error Parsing JSON Response Body"
const MSG_ERR_POST_HTTP = "Error Post Http"
const MSG_ERR_CLIENT_UNAUTHORIZE = "Client UnAuthorize"
const MSG_ERR_PARAM_NOT_FOUND = "Parameter Not Found"
const MSG_ERR_URL_NOT_FOUND = "Rest URL Not Found"
const MSG_ERR_WRONG_FORMAT = "Wrong Format"
